// THIS FILE IS GENERATED BY GO GENERATE.
// DO NOT EDIT THIS FILE BY HAND.

/**
scrape-elasticsearch is a HTTP Agent scraping Prometheus endpoints, which
forwards the elements to Elasticsearch.
Usage:
    scrape-elasticsearch [options]
Available options:
    -config PATH       Path to configuraiton file
    -username NAME     username to grant access token to connect firehose
    -password PASS     password to grant access token to connect firehose
    -worker NUM        Number of producer worker. Default is number of CPU core
    -debug             Output event to stdout instead of producing message to kafka
    -log-level LEVEL   Log level. Default level is INFO (DEBUG|INFO|ERROR)
*/
package cli
